name:                eveff
version:             1.0.0.0
github:              "xnning/eveff"
license:             MIT
author:              "Daan Leijen, Ningning Xie"
maintainer:          "xnning@hku.hk;daan@microsoft.com"
copyright:           "(c) 2020, Microsoft Research, Daan Leijen, Ningning Xie"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Efficient effect handlers based on evidence translation.
category:            Control, Effect

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  See the "Control.Ev.Eff" module or README.md for further information


dependencies:
- base >= 4.7 && < 5
- primitive
- ghc-prim

library:
  source-dirs: src
  ghc-options:
    - -O2 -fspec-constr-keen
  
benchmarks:
  TestState:
    source-dirs:         benchmark
    main:                TestState.hs
    ghc-options:
    - -main-is TestState
    - -O2
    - -Wno-simplifiable-class-constraints
    dependencies:
    - containers
    - mtl
    - eveff
    - criterion
    - extensible-effects
    - fused-effects

  TestError:
    source-dirs:         benchmark
    main:                TestError.hs
    ghc-options:
    - -main-is TestError
    - -O2 
    - -Wno-simplifiable-class-constraints
    dependencies:
    - containers
    - mtl
    - eveff
    - criterion
    - extensible-effects
    - fused-effects

  TestLayer:
    source-dirs:         benchmark
    main:                TestLayer.hs
    ghc-options:
    - -main-is TestLayer
    - -O2
    - -Wno-simplifiable-class-constraints
    dependencies:
    - containers
    - mtl
    - eveff
    - criterion
    - extensible-effects
    - fused-effects

  TestPyth:
    source-dirs:         benchmark
    main:                TestPyth.hs
    ghc-options:
    - -main-is TestPyth
    - -O2
    - -Wno-simplifiable-class-constraints
    dependencies:
    - containers
    - mtl
    - eveff
    - criterion
    - extensible-effects
    - fused-effects
